### ISSUE TITLE
ImportCost fails when file uses decorators

### ISSUE THREAD

**Issue by deevus** [yardnsm/vim-import-cost#2]
I'm using the `react-redux/connect` decorator 

```
vim-import-cost: [error] SyntaxError: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead. (110:0)
```

**Comment by yardnsm** [comment]
Hey @deevus, sorry for the late response.

I tried to reproduce the issue with the [original plugin for VS code](https://github.com/wix/import-cost/tree/master/packages/vscode-import-cost), and it also persists there. Since this vim plugin uses the same [package](https://github.com/wix/import-cost/tree/master/packages/import-cost) used to calculate the size of the modules, this issue is related to it. You can open a new issue there if you wish to.

Thanks!
